=== philip5/XML-Praktikum/src/Mancala.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT game (finished,gameID,curplayer,slot*,player*)>
	<!ELEMENT finished (#PCDATA)>
	<!ELEMENT gameID (#PCDATA)>
	<!ELEMENT curplayer (#PCDATA)>
	<!ELEMENT slot (owner,count,store,stone*)>
	<!ATTLIST slot ID CDATA #REQUIRED>
		<!ELEMENT ID (#PCDATA)>
		<!ELEMENT owner (#PCDATA)>
		<!ELEMENT count (#PCDATA)>
		<!ELEMENT store (#PCDATA)>
		<!ELEMENT stone (color)>
		<!ATTLIST stone Id CDATA #REQUIRED>
			<!ELEMENT color (#PCDATA)>
		
	<!ELEMENT player (#PCDATA)>
	<!ATTLIST player playerID CDATA #REQUIRED>

=== philip5/XML-Praktikum/bin/Mancala.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "Mancala.dtd">

<game> 
	<finished>0</finished>
	<gameID>0</gameID>
	<curplayer>1</curplayer>
	
	<slot ID = "0"> 
		<owner>1</owner> 
      	<count>0</count> 
      	<store>1</store>
	</slot> 
	
	<slot ID = "7"> 
		<owner>2</owner> 
      	<count>0</count> 
      	<store>1</store>
      	<stone Id = "1">
      		<color>#0000FF</color>
      	</stone>
      	<stone Id = "2">
      		<color>#008000</color>
      	</stone>
      		<stone Id = "3">
      		<color>#FF0000</color>
      	</stone>
      	<stone Id = "4">
      		<color>#FFFF00</color>
      	</stone>
	</slot> 
	
	<slot ID = "1"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
      	<stone Id = "1">
      		<color>	#0000FF</color>
      	</stone>	
  	</slot>
  	
  	<slot ID = "2"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
    
    <slot ID = "3"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "4"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "5"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "6"> 
     	<owner>1</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "8"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "9"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
    
    <slot ID = "10"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "11"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "12"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
  	<slot ID = "13"> 
     	<owner>2</owner> 
      	<count>4</count> 
      	<store>0</store>
  	</slot>
  	
   <player playerID = "1">
   </player> 
   <player playerID = "2">
   </player> 
</game>
